name: Update Files Every 24 Hours
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - .github/workflows/build.yml
  workflow_dispatch:
  schedule: 
    - cron:  '0 12 * * *' 

jobs:
  update-files-then-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
            
      - name: download action
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://github.com/mangoclover/domain-list-custom/raw/master/.github/workflows/build.yml
          file-name: .github/workflows/build.yml

      - name: download common.go
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://raw.githubusercontent.com/mangoclover/domain-list-custom/master/common.go
          file-name: common.go   
          
      - name: download go.mod
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://raw.githubusercontent.com/mangoclover/domain-list-custom/master/go.mod
          file-name: go.mod

      - name: download go.sum
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://raw.githubusercontent.com/mangoclover/domain-list-custom/master/go.sum
          file-name: go.sum
  
      - name: download listinfo.go
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://raw.githubusercontent.com/mangoclover/domain-list-custom/master/listinfo.go
          file-name: listinfo.go

      - name: download listinfomap.go
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://raw.githubusercontent.com/mangoclover/domain-list-custom/master/listinfomap.go
          file-name: listinfomap.go
 
      - name: download main.go
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://raw.githubusercontent.com/mangoclover/domain-list-custom/master/main.go
          file-name: main.go

      - name: download trie.go
        uses: carlosperate/download-file-action@v1.0.3
        with: 
          file-url: https://raw.githubusercontent.com/mangoclover/domain-list-custom/master/trie.go
          file-name: trie.go

      - name: Commit Changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then 
              exit 0
          else 
              git add .
              git config --local user.email "48041092+mangoclover@users.noreply.github.com"
              git config --local user.name "github-action[bot]"
              git commit -m "Updated at $(date)" -a
          fi
            
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
